#!/usr/bin/env bun
/**
 * 🔐 PASSWORD GENERATOR LIVE TEST
 */

import { generate_password } from '../packages/bridge/src/tools/generated/generate_password.ts';

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║      🔐 PASSWORD GENERATOR LIVE TEST 🔐                      ║
║                                                               ║
║  Testing autonomously generated tool!                        ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`);

console.log(`\n🧪 Test 1: Default Password (12 chars, all sets)\n`);
const test1 = await generate_password({});
console.log(`   Result: ${test1.data}`);
console.log(`   Success: ${test1.success}\n`);

console.log(`🧪 Test 2: Long password (24 chars)\n`);
const test2 = await generate_password({ length: 24 });
console.log(`   Result: ${test2.data}`);
console.log(`   Success: ${test2.success}\n`);

console.log(`🧪 Test 3: Numbers only (16 chars)\n`);
const test3 = await generate_password({
  length: 16,
  uppercase: false,
  lowercase: false,
  numbers: true,
  special_chars: false,
});
console.log(`   Result: ${test3.data}`);
console.log(`   Success: ${test3.success}\n`);

console.log(`🧪 Test 4: Letters only (no numbers/special)\n`);
const test4 = await generate_password({
  length: 20,
  uppercase: true,
  lowercase: true,
  numbers: false,
  special_chars: false,
});
console.log(`   Result: ${test4.data}`);
console.log(`   Success: ${test4.success}\n`);

console.log(`🧪 Test 5: Error Test (too short)\n`);
const test5 = await generate_password({ length: 5 });
console.log(`   Success: ${test5.success}`);
console.log(`   Error: ${test5.error}\n`);

console.log(`🧪 Test 6: Error Test (no character sets)\n`);
const test6 = await generate_password({
  uppercase: false,
  lowercase: false,
  numbers: false,
  special_chars: false,
});
console.log(`   Success: ${test6.success}`);
console.log(`   Error: ${test6.error}\n`);

console.log(`
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║         ✅ ALL TESTS COMPLETED!                              ║
║                                                               ║
║  The autonomously generated tool works perfectly!            ║
║                                                               ║
║  Generated by: 🦙 Groq (Llama 3.3 70B)                       ║
║  Cost: FREE!                                                  ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
`);
